import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

import { Chewy } from "next/font/google";

import "./globals.css";
import CustomFooter from "@/components/custom-footer";

const chewy = Chewy({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Bluey World Stripe Demo",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en" className={chewy.className}>
      <body>
        <div className="flex flex-col bg-cyan-400 min-w-screen min-h-screen text-white text-center items-center justify-center">
          {children}
          <Analytics />
          <SpeedInsights />
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
