// THIS CODE GENERATED BY CLAUDE PRO

// Types for the Claude response
interface ClaudeResponse {
  content: Array<{
    type: string;
    text: string;
  }>;
}

// Types for the quiz
interface Answer {
  text: string;
  correct: boolean;
}

interface Question {
  question: string;
  answers: Answer[];
}

export function parseClaudeQuizResponse(response: ClaudeResponse): Question[] {
  // Get the text content from the first content block
  const textContent = response.content[0].text;
 
  // Find the JSON array string using regex
  const jsonMatch = textContent.match(/\[\s*\{[\s\S]*\}\s*\]/);
  
  if (!jsonMatch) {
    throw new Error('No quiz array found in response');
  }
  
  try {
    // Parse the JSON array string
    const questions: Question[] = JSON.parse(jsonMatch[0]);
    return questions;
  } catch (error) {
    throw new Error(`Failed to parse quiz questions: ${error}`);
	}
}